# Generated by Django 4.2 on 2023-05-03 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.FileField(blank=True, upload_to="avatars/%Y/%m/%d/%H/", verbose_name="Avatar"),
        ),
        migrations.AddField(
            model_name="user",
            name="channel_description",
            field=models.TextField(blank=True, verbose_name="Channel Description"),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Required. 30 characters or fewer. Alphabetical characters only.",
                max_length=30,
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^[A-Za-z]{2,30}$")],
                verbose_name="First Name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Required. 30 characters or fewer. Alphabetical characters only.",
                max_length=30,
                null=True,
                validators=[django.core.validators.RegexValidator(regex="^[A-Za-z]{2,30}$")],
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=30,
                unique=True,
                verbose_name="Username",
            ),
        ),
    ]
