# Generated by Django 4.2 on 2023-05-03 11:35

from django.db import migrations, models
import view_it.users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar_user_channel_description_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Required. Must be an unique and valid email address.",
                max_length=254,
                unique=True,
                validators=[view_it.users.validators.validate_unique_email],
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Required. 30 characters or fewer. Alphabetical characters only.",
                max_length=30,
                null=True,
                validators=[view_it.users.validators.validate_name],
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Required. 30 characters or fewer. Alphabetical characters only.",
                max_length=30,
                null=True,
                validators=[view_it.users.validators.validate_name],
                verbose_name="Last Name",
            ),
        ),
    ]
