# Generated by Django 4.2.1 on 2023-05-05 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import view_it.videos.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Videos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url_slug", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=200, verbose_name="Video Title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Video Description")),
                (
                    "file",
                    models.FileField(
                        help_text="Required. Supported file types are: .mp4, .webm, and .ogv",
                        upload_to="videos/%Y/%m/%d/%H/",
                        validators=[view_it.videos.validators.validate_video_file_type],
                        verbose_name="Video File Path",
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True,
                        help_text="Required. Supported file types are: .jpg, .jpeg, .png, and .gif",
                        null=True,
                        upload_to="thumbnails/%Y/%m/%d/%H/",
                        validators=[view_it.videos.validators.validate_video_thumbnail_file_type],
                        verbose_name="Thumbnail File Path",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")], default="public", max_length=10
                    ),
                ),
                ("uploaded_timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Video Upload Timestamp")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
            },
        ),
    ]
